# Generated by Django 3.2.7 on 2021-09-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profiles/user-default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
