# Generated by Django 3.2.7 on 2021-09-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donor', '0002_alter_blooddonor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
